spring:
  datasource:
    url: jdbc:h2:mem:product_rating
    driverClassName: org.h2.Driver
    username: admin
    password: healthy
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8001